// Generated by the WOLips Templateengine Plug-in at Feb 3, 2014 1:25:28 PM
package com.ksroom.components;

import com.webobjects.appserver.WOContext;
import com.webobjects.foundation.NSTimestamp;

import er.extensions.components.ERXComponent;

public class Main extends ERXComponent {
  private static final long serialVersionUID = 1L;

  public Main(WOContext context) {
    super(context);
  }

  public void setMyTextForDisplay(String myTextForDisplay) {
    this.myTextForDisplay = myTextForDisplay;
  }
  public String myTextForDisplay() {
    return myTextForDisplay;
  }
  private String myTextForDisplay = "Hello World from the Java world";

  /**
   * @return the now
   */
  public NSTimestamp now() {
    return new NSTimestamp();
  }


}