// Generated by the WOLips Templateengine Plug-in at Feb 3, 2014 1:25:28 PM
package com.ksroom;

import com.webobjects.foundation.NSLog;

import er.extensions.appserver.ERXApplication;

public class Application extends ERXApplication {
	private int mainPageCounter;

  public static void main(String[] argv) {
    ERXApplication.main(argv, Application.class);
  }

  
  
  public Application() {
    NSLog.out.appendln("Welcome to " + name() + " !");
    /* ** put your initialization code in here ** */
    setAllowsConcurrentRequestHandling(true);
    
    mainPageCounter = 0;
  }

  public int mainPageCounter() {
	  return mainPageCounter;
  }
  
  public void incrementMainPageCounter() {
	  mainPageCounter++;
  }

}
