// Generated by the WOLips Templateengine Plug-in at Feb 3, 2014 1:25:28 PM
package com.ksroom;

import com.ksroom.components.Main;
import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WORequest;
import com.webobjects.appserver.WODirectAction;


public class DirectAction extends WODirectAction {
	public DirectAction(WORequest request) {
		super(request);
	}

	public WOActionResults defaultAction() {
		return pageWithName(Main.class.getName());
	}
}
