// Generated by the WOLips Templateengine Plug-in at Feb 3, 2014 1:25:28 PM
package com.ksroom;

import er.extensions.appserver.ERXSession;

public class Session extends ERXSession {
  private static final long serialVersionUID = 1L;

  public Session() {
  }
}
