// Generated by the WOLips Templateengine Plug-in at Feb 3, 2014 1:25:28 PM
package com.ksroom;

import com.ksroom.components.EColor;
import com.ksroom.components.ISampleInterface;

import er.extensions.appserver.ERXSession;

public class Session extends ERXSession implements ISampleInterface{

  private static final long serialVersionUID = 1L;

  public Session() {
  }

  @Override
  public EColor backgroundColor() {
    return EColor.Red;
  }



}
