// Generated by the WOLips Templateengine Plug-in at Feb 3, 2014 1:25:28 PM
package your.app.components;


import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

public class Main extends WOComponent {
	private static final long serialVersionUID = 1L;

	public Main(WOContext context) {
		super(context);
	}

	private String myTextForDisplay = "Hello World from the Java world";
	
	public String myTextForDisplay() {
	return myTextForDisplay;
	}
	
	public void setMyTextForDisplay(String myTextForDisplay) {
this.myTextForDisplay = myTextForDisplay;
	}
	
}