// Generated by the WOLips Templateengine Plug-in at Feb 3, 2014 1:25:28 PM
package your.app;

import com.webobjects.appserver.WOSession;

public class Session extends WOSession {
	private static final long serialVersionUID = 1L;

	public Session() {
	}
}
